### ISSUE TITLE
Crashing on Launch - iPhone 5S iOS 7 and iPad Air iOS 7 Simulator 

### ISSUE THREAD

**Issue by brbgyn** [D-32/DMPasscode#14]
After implementing DMPasscode in my project, iPhone 5S iOS 7 Simulator and iPad Air iOS 7 Simulator crashes on launch.

Console error:

dyld: Symbol not found: _objc_isAuto
  Referenced from: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
  Expected in: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.1.sdk/usr/lib/libobjc.A.dylib
 in /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
(lldb)

I'm sure it has to do with TouchID (iPhone 5S and iPad Air) and iOS 7 (since iOS 8 doesn't crash).

I found this thread on stack overflow about it:

http://stackoverflow.com/questions/26505658/ios-simulator-7-1-crash-running-on-yosemite-with-weak-linked-new-frameworks-sym

Have you experienced that ? Is it a xcode bug in Yosemite ?

Thanks

**Comment by dpopov** [comment]
To my knowledge this library currently doesn't support versions earlier than 8.0. It relies on LocalAuthentication which is not available before iOS 8. We added macro to let it compile but it will still crash.

**Comment by dpopov** [comment]
When I have time I will work on this but not sure when this will happen

**Comment by brbgyn** [comment]
Thank you

**Comment by D-32** [comment]
Actually it does support iOS 7. You just need to compile it with the newest Xcode / iOS 8 SDK. I think @dpopov added an ifdef, so maybe it even works with an older SDK.
Anyway, I'm using it in my app BitStore which works fine on iOS 7.
---
It seems to be a bug in Xcode, just use the 5 instead of the 5S (7.0 / 7.1) Simulator and it all works fine.
"If an app is weak linked against frameworks new in iOS 8 SDK and OS X 10.10 SDK, it may fail to run if the run destination is an iOS Simulator for older iOS runtimes and the host system is running OS X Yosemite. (17807439)"
